kind: pipeline
type: docker
name: build

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    environment:
      SSH_KEY:
        from_secret: deploy_key
    commands:
      - mkdir -p /root/.ssh/
      - echo "$SSH_KEY" > /root/.ssh/id_rsa
      - chmod -R 600 /root/.ssh/
      - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - git clone -v git@github.com:IricBing/megrez.git .
    when:
      branch:
        - master

  - name: build
    image: plugins/docker
    settings:
      repo: iricbing/megrez
      username: iricbing
      password: zh.2015.
      tags: latest
      no_cache: true
    when:
      branch:
        - master

---
kind: pipeline
type: exec
name: clear

clone:
  disable: true

steps:
  - name: image
    commands:
      - docker image prune -a
    when:
      branch:
        - master

depends_on:
  - build

---
kind: pipeline
type: ssh
name: deploy

clone:
  disable: true

server:
  host: 101.42.135.206
  user: ubuntu
  password:
    from_secret: server_password

steps:
  - name: pull
    commands:
      - docker pull iricbing/megrez:latest
    when:
      branch:
        - master

  - name: kill
    commands:
      - docker stop megrez
    when:
      branch:
        - master

  - name: start
    commands:
      - docker run -d --rm --name megrez -p 8080:8080 iricbing/megrez
    when:
      branch:
        - master

  - name: clear image
    commands:
      - docker image prune -a
    when:
      branch:
        - master

depends_on:
  - clear

---
kind: pipeline
type: docker
name: notify

clone:
  disable: true

steps:
  - name: email
    image: drillster/drone-email
    settings:
      subject: 'Drone build: [{{ build.status }}] {{ repo.name }} ({{ repo.branch }}) #{{ build.number }}'
      host: smtp.qq.com
      port: 465
      from: 
        from_secret: email_user
      username:
        from_secret: email_user
      password:
        from_secret: email_password
      recipients: iricbing@gmail.com,3100790937@qq.com
      # recipients_only: true
    when:
      branch:
        - master
      status:
        - success
        - changed
        - failure

depends_on:
  - deploy