kind: pipeline
type: docker
name: build

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: iricbing/megrez
      username: iricbing
      password: zh.2015.
      tags: latest
      no_cache: true
    when:
      branch:
        - master

---
kind: pipeline
type: exec
name: clear

clone:
  disable: true

steps:
  - name: clean image
    commands:
      - docker image ls
