kind: pipeline
type: docker
name: build

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: registry.cn-shanghai.aliyuncs.com/virtualbing/megrez
      registry: registry.cn-shanghai.aliyuncs.com
      username: iricbing
      password: Git.2016.
      tags: latest
      auto_tag_suffix: linux-amd64
      no_cache: true
    when:
      branch:
        - master

---
kind: pipeline
type: exec
name: clear

platform:
  os: linux
  arch: amd64

steps:
  - name: clean image
    commands:
      - docker image prune -a
