version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.31.1
    container_name: prometheus
    hostname: prometheus
    restart: always
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus-config:/etc/prometheus
      - ./prometheus-rules:/usr/local/prometheus/rules

  node_exporter:
    # image: quay.io/prometheus/node-exporter:latest
    image: prom/node-exporter:v1.3.1
    container_name: node_exporter
    hostname: node_exporter
    restart: always
    network_mode: host
    pid: host
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'